services:
  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - REDIS_INTERNAL_HOST=internal-redis:6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - internal-redis
    networks:
      - smartcache-net

  internal-redis:
    image: redis:7
    networks:
      - smartcache-net

networks:
  smartcache-net:
